name: Notify Branch Owners

on:
  schedule:
    - cron: '17 12 * * *'  # Runs every day at 10:00 AM UTC

jobs:
  notify-branch-owners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get all branches
        id: get_branches
        run: |
          branches=$(git for-each-ref --format='%(refname:short)' refs/heads/)
          echo "branches=$branches" >> $GITHUB_ENV
          echo "DEBUG: Found branches: $branches"
